name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install docker
        run: sudo chmod +x install_docker && sudo ./install_docker
      - name: Check docker version
        run: sudo docker -v
      - name: Check docker-compose version
        run: sudo docker-compose -v
